# Simplest possible theme for regression testing docreset.css and docset.css
# Purposely doesn't use "docstart.css" 
stylesheets = ["docreset.css","docset.css", "docstart.css", "plain.css", ] 

[header]                                                               
markdownfile="header.md"                          

[nav]                                                                           
markdownfile="nav.md"                                                           
   
[aside]
markdownfile="aside.md"
         
[footer] 
markdownfile="footer.md"


