Branding = "Debut theme"
Description = ""
Stylesheets = ["tufte.min.css", "layout.css","skin.css", "sage.css" ]
#Stylesheets = ["reset.css", "tufte.min.css", "fonts.css", "layout.css", "skin.css", "sage.css"]
PathName = ""

[Nav]
  HTML = ""
  File = "nav.md"

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
