
stylesheets = [ "docreset.css","docset.css","docstart.css", "marlow.css" ]
[nav]
markdownfile = "nav.md"

[header]
markdownfile = "header.md"

[footer]
markdownfile = "footer.md"

[aside]
markdownfile = "aside.md"



