Stylesheets = ["reset.css", "fonts.css", "layout.css", "theme-light.css", "roma.css"]
PathName = ""

[Nav]
  HTML = ""
  File = ""

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
