
stylesheets = [ "docreset.css","docset.css","docstart.css", "tree.css" ]
[nav]
markdownfile = "nav.md"

[header]
markdownfile = "header.md"

[footer]
markdownfile = "footer.md"

[aside]
markdownfile = "aside.md"

# https://icongr.am/fontawesome/leaf.svg?size=256&color=00FF00

