Branding = "Debut Home Page theme"
Stylesheets = ["sizes.css", "home.css", "theme-light.css", "responsive.css"]
#rootstylesheets = [ "reset.css","fonts.css","layout.css" ]



PathName = ""

[Nav]
  HTML = ""
  #File = "nav.md"

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
