
stylesheets = [ "docreset.css","docset.css","docstart.css","pro.css" ]
name="NewClean"

[header]
#html = "<header><h1>hello, world.</h1></header>"
markdownfile = "header.md"

[footer]
#html = "<footer>HTML Override footer</footer>"
markdownfile = "footer.md"

[aside]
#html = "<h3>Now, as an aside</h3>"
markdownfile = "aside.md"



