stylesheets = [ "docreset.css","docset.css","docstart.css", "personality.css"  ]

[nav]
markdownfile = "nav.md"

[header]
markdownfile = "header.md"

[footer]
markdownfile = "footer.md"

[aside]
markdownfile = "aside.md"



