
stylesheets = [ "docreset.css","docset.css","docstart.css", "recipe.css" ]

# Skin.css would be the color overrides.
skin = ""

[nav]
#markdownfile = "nav.md"

[header]
#html="<header><img src='foo.png' alt='Homestyle Fusion logo'></header>"
markdownfile = "header.md"

[footer]
markdownfile = "footer.md"

[aside]
markdownfile = "aside.md"



