Name = "mysite"
Branding = ""
CommonSubDir = ""
Language = "en"
Mode = ""
Theme = ""
AssetDir = ""
BaseDir = ""
ExcludeDirs = [ ".mb", ".sample", ".common"]
Publish = ".pub"
Headers = ".headers"
ThemeDir = "/Users/tom/code/mb/.mb/themes"
Ganalytics = ""

[MarkdownOptions]
  HighlightStyle = ""

[Author]
  FullName = ""
  URL = ""

[Company]
  Name = ""
  URL = ""
  HeaderLogo = ""

[Social]
  DeviantArt = ""
  Facebook = ""
  Github = ""
  Gitlabs = ""
  Instagram = ""
  LinkedIn = ""
  Pinterest = ""
  Reddit = ""
  Tumblr = ""
  Twitter = ""
  Weibo = ""
  YouTube = ""
