Name = "mysite"
ExcludeDirs = [ ".mb", ".sample", ".common"]
Publish = ".pub"
Headers = ".headers"
ThemeDir = ".mb/themes"
Ganalytics = ""

[MarkdownOptions]
  HighlightStyle = "autumn"

[Author]
  FullName = ""
  URL = ""

[Company]
  Name = ""
  URL = ""
  HeaderLogo = ""

[Social]
  DeviantArt = ""
  Facebook = ""
  Github = ""
  Gitlabs = ""
  Instagram = ""
  LinkedIn = ""
  Pinterest = ""
  Reddit = ""
  Tumblr = ""
  Twitter = ""
  Weibo = ""
  YouTube = ""
